# Generated by Django 3.2.4 on 2021-06-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='text',
            field=models.CharField(default='deliverd soon', max_length=50),
        ),
    ]
