# Generated by Django 3.2.4 on 2021-06-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210624_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='confirm_password',
            field=models.CharField(default=1, max_length=500),
        ),
    ]
